insert into albums (artist,title,language_type) values 
('Arsen Dedić','25 Greatest Hits',0),
('Atomsko Sklonište','Mentalna Higijena',0),
('Atomsko Sklonište','Zabranjeno Snimanje',0),
('Azra','Ravno do dna',0),
('Azra','Između krajnosti',0),
('Azra','Krivo srastanje',0),
('Azra','Azra',0),
('Azra','Kad fazani lete',0),
('Azra','Filigranski pločnici',0),
('Branimir Štulić','Balkanska rapsodija',0),
('Bajaga','Jahači Magle',0),
('Drago Mlinarec','Tako Lako',0),
('Drago Mlinarec','Pomaknuto',0),
('Đorđe Balašević','Tri posleratna druga',0),
('Đorđe Balašević','Panta Rei',0),
('Đorđe Balašević','Pub',0),
('Đorđe Balašević','Bezdan',0),
('Bombardiranje NM/NM/NM Yorka','Bombardiranje NM/NM/NM Yorka',0),
('Buldožer','Zabranjeno Plakatiranje',0),
('Buldožer','Nevino srce',0),
('Buldožer','Izlog Jeftinih Slatkiša',0),
('Buldožer','Pljuni istini u oči',0),
('Daniel','Bio sam naivan',0),
('Dee Dee Mellow','Dee Dee Mellow',0),
('Disciplina Kičme','Zeleni Zub na planeti dosade',0),
('Disciplina Kičme','Sviđa mi se da ti ne bude prijatno',0),
('Disciplina Kičme','Ja imam Šarene Oči',0),
('Disciplina Kičme','Dečja Pesma',0),
('Disciplina Kičme','Opet',0),
('Električni Orgazam','Električni Orgazam',0),
('Električni Orgazam','Lišće prekriva Lisabon',0),
('Električni Orgazam','Les Chansones Populaires',0),
('Električni Orgazam','Distorzija',0),
('Električni Orgazam','Elektriczny Orgazm',0),
('Film','Signali u noći',0),
('Haustor','Bolero',0),
('Haustor','Haustor',0),
('Haustor','Treći svijet',0),
('Hladno Pivo','Džinovski',0),
('Idoli','Odbrana i poslednji dani',0),
('Jani Kovačić','Jani Kovačić',0),
('Kud Idijoti','Mi smo ovdje samo zbog para',0),
('Laboratorija Zvuka','Telo',0),
('Lačni Franz','Slon Med Porcelanom',0),
('Lačni Franz','Nemoj mi dihat za ovratnik',0),
('Lačni Franz','Adijo pamet',0),
('Lačni Franz','Sirene tulijo',0),
('Amy Winehouse','Back to black',1),
('The Beach Boys','Sunflower',1),
('Blues Roots','Give Me the Blues',1),
('Bob Dylan','Pat Garret & BillY The Kid',1),
('Bob Dylan','Slow Train Coming',1),
('Bob Dylan','The Times They are A-changin',1),
('Beatles','Sgnt Peppers Lonely Hearts Club Band',1),
('Beatles','Beatles for sale',1),
('Buena VistaSocial Club','Buena VistaSocial Club',1),
('Jacques Brell','Brell',1),
('The Clash','The Clash',1),
('The Clash','Combat Rock',1),
('The Clash','Sandinista',1),
('The Clash','The story of THE CLASH',1),
('Cure','Disintegrations',1),
('Culture Club','From Luxury to Heartache',1),
('Chris Rea','The Road to Hell',1),
('Dead Kennedys','In god we trust',1),
('Dire Straits','Money for nothing',1),
('Dire Straits','Making movies',1),
('Dire Straits','Communique',1),
('Dire Straits','Brothers in arms',1),
('David Bowie','Ziggy Stardust',1),
('David Bowie','Changes One BOWIE',1),
('David Bowie','Absolute Beginners',1),
('Doors','Waiting for the sun',1),
('Edith Piaf','Cest la vie',1),
('Eurythmics','Be yourself tonight',1),
('Eurythmics','1984',1),
('Eurythmics','Revenge',1),
('Eurythmics','Touch',1),
('Eurythmics','Savage',1),
('Falco','FALCO',1),
('Jimi Hendrix','The cry of love',1),
('Jean Michel Jare','Equinoxe',1),
('Jean Michel Jare','Les chants magnetiques',1),
('Jean Michel Jare','Oxygene',1),
('Johnny Cash','Chameleon',1),
('Johnny Cash','The last gunfighter ballad',1),
('Joy Division','FacusP',1),
('La Bamba P','La Bamba P',1),
('Lou Reed','New York',1),
('Lou Reed','Transformer',1),
('Malcolm McLaren','Fans',1),
('Mano Negra','Putas Fever',1),
('Modern Talking','1st Album',1),
('Modern Talking','2nd Let,s talk about love',1),
('Modern Talking','3rd Album Ready for Romance',1),
('Morphine','Good',1),
('Morphine','cure for pain',1),
('Morphine','Like Swimming',1),
('Nick Cave','Henrys dream',1),
('Nick Cave','Let Love in',1),
('Music From the Body','Music From the Body',1),
('PhoneboxVandals','Damned Dye Hard',1),
('Pink Floyd','Wish You Were Here',1),
('Pink Floyd','The final cut',1),
('Pink Floyd','Delicate Sound of Thunder',1),
('Pink Floyd','A Momentary Laps of Reason',1),
('Pink Floyd','The Dark Side of the Moon ',1),
('Pink Floyd','The Wall',1),
('Pink Floyd','A Collection of Great Dance Songs',1),
('Pink Floyd','Meddle',1),
('Pink Floyd','A Nice Pair',1),
('Pixies','come on Pilgrim',1),
('Pixies','Doolitle',1),
('Pixies','Bossanova',1),
('The Pletters','Somebody loves me',1),
('Paul Simon','Graceland the Remixes',1),
('Paul Simon','Graceland',1),
('Simon & Garfunkel','Sounds of Silence',1),
('Pogues','Hells Ditch',1),
('Prince','Purple Rain',1),
('Queen','LIVE Magic',1),
('Rosane Cash','Retrospective (1979-1989)',1),
('Rita Coolidge','Never let You go',1),
('RAMONES','Ramones',1),
('RAMONES','Leave Home ',1),
('RAMONES','Rocket to Rusia',1),
('Roxy Music','Greatest Hits',1),
('Roxy Music','Manifesto',1),
('Sex Pistols','Flogging a Dead Horse',1),
('Sex Pistols','Where are You in 77',1),
('Sex Pistols','Never mind the bollocks heres the Seks Pistols',1),
('The Shadows','20 Golden Greats',1),
('The Smiths','Hatful of Hollow',1),
('The Smiths','The Queen is Dead',1),
('The Smiths','Louder Than Bombs',1),
('The Smiths','Rank',1),
('Stray Cats','Stray Cats',1),
('Tina Turner','Private Dancer',1),
('The Stranglers','No More Heroes',1),
('The Stranglers','Aural Sculpture',1),
('Tom Waits','Franks Wild Years',1),
('Tom Waits','Big Time',1),
('Tom Waits','Blood Money',1),
('Tom Waits','SwordFishTrombones',1),
('Tom Waits','Mule Variations',1),
('Tom Waits','Closing Time',1),
('Tom Waits','Real Gone',1),
('Tom Waits','Rain Dogs',1),
('Tom Waits','Alice',1),
('Trainspotting','Trainspotting',1),
('UB 40','Labour of love',1),
('The Velvet Underground & Nico','Andy Warhol',1),
('Wham','Fantastic',1);
