insert into record_copyes (album_id,owner_id,media_condition,sleeve_condition,sound_condition,comment_private,comment_public,duplicate) values 
(1,1,'NM','NM','NM','218kn(29€),','',''),
(2,1,'NM','?','?','moja stara,','',''),
(3,1,'VG+','NM','NM','moja stara,obrisana, oprana','',''),
(4,1,'NM','NM','NM',',','',''),
(5,1,'NM','VG+','G','Jurman,obrisana, oprana','šuška',''),
(6,1,'VG+','NM','NM','Jurman,obrisana','',''),
(7,1,'VG+','NM','NM','Jurman,obrisana','',''),
(8,1,'NM','NM','NM','Jurman,obrisana','',''),
(9,1,'NM','NM','VG+','Jurman,obrisana','',''),
(10,1,'NM','NM','VG+','Jurman,obrisana','',''),
(11,1,'VG+','NM','NM','moja stara,obrisana','',''),
(12,1,'G','G','G','Jurman,obrisana, oprana','preskače str1. i 2.',''),
(13,1,'NM','VG','VG+','Jurman,obrisana, oprana','',''),
(14,1,'NM','?','?','moja stara,','',''),
(15,1,'NM','?','?','moja stara,','',''),
(16,1,'NM','?','?','moja stara,','',''),
(17,1,'NM','?','?','moja stara,','',''),
(18,1,'G','-G','-G','Jurman,obrisana','pucka jako',''),
(19,1,'G','-VG+','-VG+','Jurman,obrisana','ogrebotina na 1. str',''),
(20,1,'NM','VG+','NM','Jurman,obrisana','ogrebotina na 1. i 2.str',''),
(21,1,'NM','VG+','VG+','Jurman,obrisana','',''),
(22,1,'G','VG','VG','Goran Barić 9€,obrisana, oprana','',''),
(22,1,'G','P','P','Jurman,obrisana','oštećena jako','1'),
(23,1,'VG+','?','?','moja stara,','',''),
(24,1,'NM','NM','NM',',','',''),
(25,1,'NM','VG+','VG+','Beograd (Deso),obrisana','malo pucka',''),
(26,1,'NM','NM','NM',',','',''),
(27,1,'G','G','VG+','Jurman,obrisana, oprana','',''),
(28,1,'VG+','NM','NM','Goran Barić 47€,obrisana, oprana','',''),
(29,1,'NM','NM','NM',',','',''),
(30,1,'NM','NM','NM',',','',''),
(31,1,'NM','NM','NM ','179kn(24€),','',''),
(32,1,'NM','VG+','NM','sajam ploča,obrisana','',''),
(33,1,'NM','NM','NM','169kn(23€),','',''),
(34,1,'NM','NM','NM',' 19NMkn(26€),','',''),
(35,1,'NA','?','?','Jurman,','nema omot',''),
(36,1,'NM','NM','NM','195kn(26€),','',''),
(37,1,'NM','NM','NM',',','',''),
(38,1,'NM','NM','NM','203kn(27€),','',''),
(39,1,'NM','NM','NM','188kn(25€),','',''),
(40,1,'NM','NM','NM','180kn(24€),','',''),
(41,1,'VG+','?','?','Jurman,obrisana, oprana','pucka, dosta dobra',''),
(42,1,'VG+','VG+','?','Jurman,obrisana','dosta dobro',''),
(43,1,'NM','VG+','VG+','Goran Barić 7€,obrisana, oprana','',''),
(44,1,'NM','VG+','?','Jurman,obrisana, oprana','',''),
(45,1,'VG','G','VG+','Jurman,obrisana, oprana','',''),
(46,1,'NM','G+','G','Jurman,obrisana, oprana','',''),
(47,1,'VG','VG+','NM','Jurman,obrisana, oprana','',''),
(48,1,'NM','NM','NM',',','',''),
(49,1,'G','VG+','G+','moja stara,obrisana, oprana','',''),
(50,1,'VG+','?','?','moja stara,','',''),
(51,1,'VG','G','VG+','sajam starina 50kn(7€),obrisana, oprana','',''),
(52,1,'NM','VG+','NM','sajam ploča 10€,obrisana','',''),
(53,1,'NM','VG','VG+','sajam starina 8€,obrisana','pucka malo',''),
(54,1,'VG+','?','?','moja stara,','',''),
(55,1,'VG','?','?','moja stara,','',''),
(56,1,'NM','NM','NM',',','',''),
(57,1,'G','G','VG','Jurman,obrisana','',''),
(58,1,'NM','NM','NM',',','',''),
(58,1,'G','?','?','moja stara,','','1'),
(59,1,'VG+','NM','NM','Jurman,obrisana, oprana','',''),
(60,1,'VG','NM','NM','Jurman,obrisana','',''),
(61,1,'VG+','G','G','Jurman,obrisana, oprana','pucka',''),
(62,1,'NM','NM','NM','sajam ploca 55€,','',''),
(63,1,'VG+','?','?','moja stara,','',''),
(64,1,'NM','NM','NM','sajam ploca PP€,','',''),
(65,1,'NM','VG+','VG+','Jurman,obrisana, oprana','',''),
(66,1,'NM','NM','NM','319kn(4P€),','',''),
(67,1,'VG','VG+','VG+','sajam starina,obrisana','',''),
(68,1,'NM','?','?','moja stara,','',''),
(69,1,'NM','NM','NM','P9€,','',''),
(70,1,'NM','NM','NM','165kn(PP€),','',''),
(71,1,'NM','NM','NM',',','',''),
(72,1,'VG+','NM','?','Srđan,obrisana oprana','',''),
(73,1,'VG','VG+','VG+','Jurman,obrisana','',''),
(74,1,'NM','NM','NM','165kn(PP€),','',''),
(75,1,'NM','NM','?','Srđan,obrisana, oprana','',''),
(76,1,'NM','NM','?','Srđan,obrisana, oprana','',''),
(77,1,'NM','NM','?','Srđan,obrisana, oprana','',''),
(78,1,'NM','NM','?','Srđan,obrisana','',''),
(79,1,'NM','NM','NM','Srđan,obrisana','',''),
(80,1,'NM','?','?','moja stara,','',''),
(81,1,'G','G','G','moja stara,obrisana, oprana','',''),
(82,1,'NM','?','?','moja stara,','',''),
(82,1,'VG+','VG+','?','Jurman,obrisana','','1'),
(83,1,'VG+','?','?','moja stara,','',''),
(84,1,'VG+','?','?','moja stara,','',''),
(85,1,'NM','NM','NM',',','',''),
(86,1,'VG+','?','?','moja stara,','',''),
(87,1,'NM','NM','NM','159kn(P1€),','',''),
(88,1,'VG+','?','?','moja stara,','',''),
(89,1,'NM','NM','NM','P69kn(36€),','',''),
(89,1,'G+','P','P','Jurman,obrisana, oprana','pucka preskace','1'),
(90,1,'NM','NM','NM','199kn(P7€),','',''),
(91,1,'NM','NM','NM','Srđan,obrisana','',''),
(92,1,'NM','NM','NM',',','',''),
(93,1,'NM','NM','NM','Srđan,obrisana, oprana','',''),
(94,1,'NM','NM','?','Srđan,obrisana, oprana','',''),
(95,1,'NM','NM','NM','moja stara,','',''),
(96,1,'NM','NM','NM',',','',''),
(97,1,'NM','NM','NM','P99kn(40€),','',''),
(98,1,'NM','NM','NM',',','',''),
(99,1,'NM','NM','NM',',','',''),
(100,1,'NM','NM','NM',',','',''),
(101,1,'VG+','P','?','moja stara,','',''),
(102,1,'NM','VG+','VG','Jurman,obrisana','',''),
(103,1,'NM','VG+','G+','Jurman,obrisana','',''),
(104,1,'VG+','NM','G','Jurman,obrisana','šuška',''),
(105,1,'VG+','NM','G','Jurman,obrisana','pucka',''),
(106,1,'VG+','NM','VG+','Jurman,obrisana','šuška malo',''),
(107,1,'VG+','VG+','NM','Jurman,obrisana','',''),
(108,1,'NM','NM','VG+','Jurman,obrisana','',''),
(109,1,'VG','VG+','G','Jurman,obrisana','šuška',''),
(110,1,'NM','NM','VG+','Jurman,obrisana','',''),
(111,1,'NM','NM','VG+','Jurman,obrisana','',''),
(112,1,'NM','NM','NM',',','',''),
(113,1,'NM','NM','NM',',','',''),
(114,1,'NM','NM','NM','P39kn(krune=kune),','',''),
(115,1,'VG','VG','VG+','moja stara,obrisana, oprana','',''),
(116,1,'NM','NM','NM','PP4kn,','',''),
(117,1,'NM','NM','NM','Srđan,','',''),
(118,1,'NM','NM','NM','191kn(P5€),','',''),
(119,1,'NM','NM','VG+','Jurman,obrisana','',''),
(120,1,'NM','NM','NM','Srđan,obrisana','',''),
(121,1,'NM','NM','NM','moja stara,obrisana','',''),
(122,1,'VG+','?','?','moja stara,','',''),
(123,1,'NM','?','?','moja stara,','',''),
(124,1,'NM','NM','NM','188kn(P5€),','',''),
(125,1,'NM','VG+','VG','Jurman,obrisana','pucka',''),
(126,1,'NM','NM','NM','179kn,','',''),
(127,1,'VG','G','G','Jurman,obrisana, oprana','pucka',''),
(128,1,'NM','NM','NM','P70kn(kune=krune),','',''),
(129,1,'NM','VG+','G','Jurman,obrisana','',''),
(130,1,'NM','NM','G','Jurman,obrisana','',''),
(131,1,'NM','P','P','Jurman,obrisana, oprana','šuška pucka',''),
(132,1,'NM','NM','NM','moja stara,','',''),
(133,1,'NM','NM','NM','165kn(PP€),','',''),
(134,1,'NM','NM','NM',',','',''),
(135,1,'NM','NM','NM',',','',''),
(136,1,'NM','NM','NM',',','',''),
(137,1,'G','P','VG+','sajam starina P0kn,obrisana, oprana','',''),
(138,1,'NM','NM','NM','moja stara,','',''),
(139,1,'G','G','G+','sajam starina,obrisana','preskače B strana',''),
(140,1,'NM','NM','NM','sajam ploča P0€,','',''),
(141,1,'NM','NM','VG+','Deklman,','',''),
(142,1,'NM','NM','NM','Deklman,','',''),
(143,1,'NM','NM','NM','P18kn(P9€),','',''),
(144,1,'NM','NM','NM','P70kn(kune=krune),','',''),
(145,1,'NM','NM','NM','P30kn(kune=krune),','',''),
(146,1,'NM','NM','NM','P00kn(kune=krune),','',''),
(147,1,'NM','NM','NM','PP0kn(kune=krune),','',''),
(148,1,'NM','NM','NM','300kn(40€),','',''),
(149,1,'NM','NM','NM','P30kn(kune=krune),','',''),
(150,1,'NM','NM','NM',',','',''),
(151,1,'VG+','NM','?','Vjeran 40.rođendan,','',''),
(152,1,'NM','NM','NM','PP5kn(30€),','',''),
(153,1,'NM','NM','?','moja stara,obrisana, oprana','','');


