use master;
go
alter database vinylbook set single_user with rollback immediate;
go
drop database if exists vinylbook;
go
create database vinylbook collate Croatian_CI_AS;
go

use vinylbook;

create table albums(
id int not null primary key identity(1,1),
title varchar(200) not null,
artist varchar(100) not null,
language_type bit
);

create table users(
id int not null primary key identity(1,1),
uname varchar(20) not null,
ulastname varchar(20) not null,
uemail varchar(50) not null,
uphone varchar(20) not null,
uaddress varchar(50) not null
);

create table record_copyes(
id int not null primary key identity(1,1),
album_id int null,
owner_id int null,
media_condition varchar(10) not null,
sleeve_condition varchar(10) not null,
sound_condition varchar(10) not null,
duplicate bit,
comment_private varchar(300),
comment_public varchar(300)
);

create table exchanges(
id int not null primary key identity(1,1),
participant_id int not null,
exchange_id int,
album_id int,
record_copy_id int, 
estatus varchar(10)
);

alter table record_copyes add foreign key (album_id) references albums(id);
alter table record_copyes add foreign key (owner_id) references users(id);
alter table exchanges add foreign key (participant_id) references users(id);
alter table exchanges add foreign key (album_id) references users(id);
alter table exchanges add foreign key (record_copy_id) references record_copyes(id);
alter table exchanges add foreign key (album_id) references albums(id);

insert into albums (artist,title,language_type) values 
('Arsen Dedić','25 Greatest Hits',0),
('Atomsko Sklonište','Mentalna Higijena',0),
('Atomsko Sklonište','Zabranjeno Snimanje',0),
('Azra','Ravno do dna',0),
('Azra','Između krajnosti',0),
('Azra','Krivo srastanje',0),
('Azra','Azra',0),
('Azra','Kad fazani lete',0),
('Azra','Filigranski pločnici',0),
('Branimir Štulić','Balkanska rapsodija',0),
('Bajaga','Jahači Magle',0),
('Drago Mlinarec','Tako Lako',0),
('Drago Mlinarec','Pomaknuto',0),
('Đorđe Balašević','Tri posleratna druga',0),
('Đorđe Balašević','Panta Rei',0),
('Đorđe Balašević','Pub',0),
('Đorđe Balašević','Bezdan',0),
('Bombardiranje NM/NM/NM Yorka','Bombardiranje NM/NM/NM Yorka',0),
('Buldožer','Zabranjeno Plakatiranje',0),
('Buldožer','Nevino srce',0),
('Buldožer','Izlog Jeftinih Slatkiša',0),
('Buldožer','Pljuni istini u oči',0),
('Daniel','Bio sam naivan',0),
('Dee Dee Mellow','Dee Dee Mellow',0),
('Disciplina Kičme','Zeleni Zub na planeti dosade',0),
('Disciplina Kičme','Sviđa mi se da ti ne bude prijatno',0),
('Disciplina Kičme','Ja imam Šarene Oči',0),
('Disciplina Kičme','Dečja Pesma',0),
('Disciplina Kičme','Opet',0),
('Električni Orgazam','Električni Orgazam',0),
('Električni Orgazam','Lišće prekriva Lisabon',0),
('Električni Orgazam','Les Chansones Populaires',0),
('Električni Orgazam','Distorzija',0),
('Električni Orgazam','Elektriczny Orgazm',0),
('Film','Signali u noći',0),
('Haustor','Bolero',0),
('Haustor','Haustor',0),
('Haustor','Treći svijet',0),
('Hladno Pivo','Džinovski',0),
('Idoli','Odbrana i poslednji dani',0),
('Jani Kovačić','Jani Kovačić',0),
('Kud Idijoti','Mi smo ovdje samo zbog para',0),
('Laboratorija Zvuka','Telo',0),
('Lačni Franz','Slon Med Porcelanom',0),
('Lačni Franz','Nemoj mi dihat za ovratnik',0),
('Lačni Franz','Adijo pamet',0),
('Lačni Franz','Sirene tulijo',0),
('Amy Winehouse','Back to black',1),
('The Beach Boys','Sunflower',1),
('Blues Roots','Give Me the Blues',1),
('Bob Dylan','Pat Garret & BillY The Kid',1),
('Bob Dylan','Slow Train Coming',1),
('Bob Dylan','The Times They are A-changin',1),
('Beatles','Sgnt Peppers Lonely Hearts Club Band',1),
('Beatles','Beatles for sale',1),
('Buena VistaSocial Club','Buena VistaSocial Club',1),
('Jacques Brell','Brell',1),
('The Clash','The Clash',1),
('The Clash','Combat Rock',1),
('The Clash','Sandinista',1),
('The Clash','The story of THE CLASH',1),
('Cure','Disintegrations',1),
('Culture Club','From Luxury to Heartache',1),
('Chris Rea','The Road to Hell',1),
('Dead Kennedys','In god we trust',1),
('Dire Straits','Money for nothing',1),
('Dire Straits','Making movies',1),
('Dire Straits','Communique',1),
('Dire Straits','Brothers in arms',1),
('David Bowie','Ziggy Stardust',1),
('David Bowie','Changes One BOWIE',1),
('David Bowie','Absolute Beginners',1),
('Doors','Waiting for the sun',1),
('Edith Piaf','Cest la vie',1),
('Eurythmics','Be yourself tonight',1),
('Eurythmics','1984',1),
('Eurythmics','Revenge',1),
('Eurythmics','Touch',1),
('Eurythmics','Savage',1),
('Falco','FALCO',1),
('Jimi Hendrix','The cry of love',1),
('Jean Michel Jare','Equinoxe',1),
('Jean Michel Jare','Les chants magnetiques',1),
('Jean Michel Jare','Oxygene',1),
('Johnny Cash','Chameleon',1),
('Johnny Cash','The last gunfighter ballad',1),
('Joy Division','FacusP',1),
('La Bamba P','La Bamba P',1),
('Lou Reed','New York',1),
('Lou Reed','Transformer',1),
('Malcolm McLaren','Fans',1),
('Mano Negra','Putas Fever',1),
('Modern Talking','1st Album',1),
('Modern Talking','2nd Let,s talk about love',1),
('Modern Talking','3rd Album Ready for Romance',1),
('Morphine','Good',1),
('Morphine','cure for pain',1),
('Morphine','Like Swimming',1),
('Nick Cave','Henrys dream',1),
('Nick Cave','Let Love in',1),
('Music From the Body','Music From the Body',1),
('PhoneboxVandals','Damned Dye Hard',1),
('Pink Floyd','Wish You Were Here',1),
('Pink Floyd','The final cut',1),
('Pink Floyd','Delicate Sound of Thunder',1),
('Pink Floyd','A Momentary Laps of Reason',1),
('Pink Floyd','The Dark Side of the Moon ',1),
('Pink Floyd','The Wall',1),
('Pink Floyd','A Collection of Great Dance Songs',1),
('Pink Floyd','Meddle',1),
('Pink Floyd','A Nice Pair',1),
('Pixies','come on Pilgrim',1),
('Pixies','Doolitle',1),
('Pixies','Bossanova',1),
('The Pletters','Somebody loves me',1),
('Paul Simon','Graceland the Remixes',1),
('Paul Simon','Graceland',1),
('Simon & Garfunkel','Sounds of Silence',1),
('Pogues','Hells Ditch',1),
('Prince','Purple Rain',1),
('Queen','LIVE Magic',1),
('Rosane Cash','Retrospective (1979-1989)',1),
('Rita Coolidge','Never let You go',1),
('RAMONES','Ramones',1),
('RAMONES','Leave Home ',1),
('RAMONES','Rocket to Rusia',1),
('Roxy Music','Greatest Hits',1),
('Roxy Music','Manifesto',1),
('Sex Pistols','Flogging a Dead Horse',1),
('Sex Pistols','Where are You in 77',1),
('Sex Pistols','Never mind the bollocks heres the Seks Pistols',1),
('The Shadows','20 Golden Greats',1),
('The Smiths','Hatful of Hollow',1),
('The Smiths','The Queen is Dead',1),
('The Smiths','Louder Than Bombs',1),
('The Smiths','Rank',1),
('Stray Cats','Stray Cats',1),
('Tina Turner','Private Dancer',1),
('The Stranglers','No More Heroes',1),
('The Stranglers','Aural Sculpture',1),
('Tom Waits','Franks Wild Years',1),
('Tom Waits','Big Time',1),
('Tom Waits','Blood Money',1),
('Tom Waits','SwordFishTrombones',1),
('Tom Waits','Mule Variations',1),
('Tom Waits','Closing Time',1),
('Tom Waits','Real Gone',1),
('Tom Waits','Rain Dogs',1),
('Tom Waits','Alice',1),
('Trainspotting','Trainspotting',1),
('UB 40','Labour of love',1),
('The Velvet Underground & Nico','Andy Warhol',1),
('Wham','Fantastic',1);

insert into users (uname,ulastname ,uemail,uphone,uaddress) values 
('Igor','Tomić','i.tomic.babinski@gmail.com','0914691495','Cetinačka 55 31000 Osijek'),
('Arsen','Turk','a.turk@gmail.com','091233334','Valjevačka 3 31000 Osijek'),
('Goran','Matoš','goran.matos@a1.hr','0914691496','Maratonska 2 10000 Zagreb'),
('Goran','Pleše','goran.plese@a1.hr','0914691488','Maratekova 89 10000 Zagreb'),
('Silvija','Turković','s.turkovic@vip.hr','0912345678','Samoborska 22 21000 Rijeka'),
('Ivana','Mihanović','i.mihanovic99@gmail.hr','091233445566','Ivekova 32 10000 Zagreb');

insert into record_copyes (album_id,owner_id,media_condition,sleeve_condition,sound_condition,comment_private,comment_public,duplicate) values 
(1,1,'NM','NM','NM','218kn(29€),','',''),
(2,1,'NM','?','?','moja stara,','',''),
(3,1,'VG+','NM','NM','moja stara,obrisana, oprana','',''),
(4,1,'NM','NM','NM',',','',''),
(5,1,'NM','VG+','G','Jurman,obrisana, oprana','šuška',''),
(6,1,'VG+','NM','NM','Jurman,obrisana','',''),
(7,1,'VG+','NM','NM','Jurman,obrisana','',''),
(8,1,'NM','NM','NM','Jurman,obrisana','',''),
(9,1,'NM','NM','VG+','Jurman,obrisana','',''),
(10,1,'NM','NM','VG+','Jurman,obrisana','',''),
(11,1,'VG+','NM','NM','moja stara,obrisana','',''),
(12,1,'G','G','G','Jurman,obrisana, oprana','preskače str1. i 2.',''),
(13,1,'NM','VG','VG+','Jurman,obrisana, oprana','',''),
(14,1,'NM','?','?','moja stara,','',''),
(15,1,'NM','?','?','moja stara,','',''),
(16,1,'NM','?','?','moja stara,','',''),
(17,1,'NM','?','?','moja stara,','',''),
(18,1,'G','-G','-G','Jurman,obrisana','pucka jako',''),
(19,1,'G','-VG+','-VG+','Jurman,obrisana','ogrebotina na 1. str',''),
(20,1,'NM','VG+','NM','Jurman,obrisana','ogrebotina na 1. i 2.str',''),
(21,1,'NM','VG+','VG+','Jurman,obrisana','',''),
(22,1,'G','VG','VG','Goran Barić 9€,obrisana, oprana','',''),
(22,1,'G','P','P','Jurman,obrisana','oštećena jako','1'),
(23,1,'VG+','?','?','moja stara,','',''),
(24,1,'NM','NM','NM',',','',''),
(25,1,'NM','VG+','VG+','Beograd (Deso),obrisana','malo pucka',''),
(26,1,'NM','NM','NM',',','',''),
(27,1,'G','G','VG+','Jurman,obrisana, oprana','',''),
(28,1,'VG+','NM','NM','Goran Barić 47€,obrisana, oprana','',''),
(29,1,'NM','NM','NM',',','',''),
(30,1,'NM','NM','NM',',','',''),
(31,1,'NM','NM','NM ','179kn(24€),','',''),
(32,1,'NM','VG+','NM','sajam ploča,obrisana','',''),
(33,1,'NM','NM','NM','169kn(23€),','',''),
(34,1,'NM','NM','NM',' 19NMkn(26€),','',''),
(35,1,'NA','?','?','Jurman,','nema omot',''),
(36,1,'NM','NM','NM','195kn(26€),','',''),
(37,1,'NM','NM','NM',',','',''),
(38,1,'NM','NM','NM','203kn(27€),','',''),
(39,1,'NM','NM','NM','188kn(25€),','',''),
(40,1,'NM','NM','NM','180kn(24€),','',''),
(41,1,'VG+','?','?','Jurman,obrisana, oprana','pucka, dosta dobra',''),
(42,1,'VG+','VG+','?','Jurman,obrisana','dosta dobro',''),
(43,1,'NM','VG+','VG+','Goran Barić 7€,obrisana, oprana','',''),
(44,1,'NM','VG+','?','Jurman,obrisana, oprana','',''),
(45,1,'VG','G','VG+','Jurman,obrisana, oprana','',''),
(46,1,'NM','G+','G','Jurman,obrisana, oprana','',''),
(47,1,'VG','VG+','NM','Jurman,obrisana, oprana','',''),
(48,1,'NM','NM','NM',',','',''),
(49,1,'G','VG+','G+','moja stara,obrisana, oprana','',''),
(50,1,'VG+','?','?','moja stara,','',''),
(51,1,'VG','G','VG+','sajam starina 50kn(7€),obrisana, oprana','',''),
(52,1,'NM','VG+','NM','sajam ploča 10€,obrisana','',''),
(53,1,'NM','VG','VG+','sajam starina 8€,obrisana','pucka malo',''),
(54,1,'VG+','?','?','moja stara,','',''),
(55,1,'VG','?','?','moja stara,','',''),
(56,1,'NM','NM','NM',',','',''),
(57,1,'G','G','VG','Jurman,obrisana','',''),
(58,1,'NM','NM','NM',',','',''),
(58,1,'G','?','?','moja stara,','','1'),
(59,1,'VG+','NM','NM','Jurman,obrisana, oprana','',''),
(60,1,'VG','NM','NM','Jurman,obrisana','',''),
(61,1,'VG+','G','G','Jurman,obrisana, oprana','pucka',''),
(62,1,'NM','NM','NM','sajam ploca 55€,','',''),
(63,1,'VG+','?','?','moja stara,','',''),
(64,1,'NM','NM','NM','sajam ploca PP€,','',''),
(65,1,'NM','VG+','VG+','Jurman,obrisana, oprana','',''),
(66,1,'NM','NM','NM','319kn(4P€),','',''),
(67,1,'VG','VG+','VG+','sajam starina,obrisana','',''),
(68,1,'NM','?','?','moja stara,','',''),
(69,1,'NM','NM','NM','P9€,','',''),
(70,1,'NM','NM','NM','165kn(PP€),','',''),
(71,1,'NM','NM','NM',',','',''),
(72,1,'VG+','NM','?','Srđan,obrisana oprana','',''),
(73,1,'VG','VG+','VG+','Jurman,obrisana','',''),
(74,1,'NM','NM','NM','165kn(PP€),','',''),
(75,1,'NM','NM','?','Srđan,obrisana, oprana','',''),
(76,1,'NM','NM','?','Srđan,obrisana, oprana','',''),
(77,1,'NM','NM','?','Srđan,obrisana, oprana','',''),
(78,1,'NM','NM','?','Srđan,obrisana','',''),
(79,1,'NM','NM','NM','Srđan,obrisana','',''),
(80,1,'NM','?','?','moja stara,','',''),
(81,1,'G','G','G','moja stara,obrisana, oprana','',''),
(82,1,'NM','?','?','moja stara,','',''),
(82,1,'VG+','VG+','?','Jurman,obrisana','','1'),
(83,1,'VG+','?','?','moja stara,','',''),
(84,1,'VG+','?','?','moja stara,','',''),
(85,1,'NM','NM','NM',',','',''),
(86,1,'VG+','?','?','moja stara,','',''),
(87,1,'NM','NM','NM','159kn(P1€),','',''),
(88,1,'VG+','?','?','moja stara,','',''),
(89,1,'NM','NM','NM','P69kn(36€),','',''),
(89,1,'G+','P','P','Jurman,obrisana, oprana','pucka preskace','1'),
(90,1,'NM','NM','NM','199kn(P7€),','',''),
(91,1,'NM','NM','NM','Srđan,obrisana','',''),
(92,1,'NM','NM','NM',',','',''),
(93,1,'NM','NM','NM','Srđan,obrisana, oprana','',''),
(94,1,'NM','NM','?','Srđan,obrisana, oprana','',''),
(95,1,'NM','NM','NM','moja stara,','',''),
(96,1,'NM','NM','NM',',','',''),
(97,1,'NM','NM','NM','P99kn(40€),','',''),
(98,1,'NM','NM','NM',',','',''),
(99,1,'NM','NM','NM',',','',''),
(100,1,'NM','NM','NM',',','',''),
(101,1,'VG+','P','?','moja stara,','',''),
(102,1,'NM','VG+','VG','Jurman,obrisana','',''),
(103,1,'NM','VG+','G+','Jurman,obrisana','',''),
(104,1,'VG+','NM','G','Jurman,obrisana','šuška',''),
(105,1,'VG+','NM','G','Jurman,obrisana','pucka',''),
(106,1,'VG+','NM','VG+','Jurman,obrisana','šuška malo',''),
(107,1,'VG+','VG+','NM','Jurman,obrisana','',''),
(108,1,'NM','NM','VG+','Jurman,obrisana','',''),
(109,1,'VG','VG+','G','Jurman,obrisana','šuška',''),
(110,1,'NM','NM','VG+','Jurman,obrisana','',''),
(111,1,'NM','NM','VG+','Jurman,obrisana','',''),
(112,1,'NM','NM','NM',',','',''),
(113,1,'NM','NM','NM',',','',''),
(114,1,'NM','NM','NM','P39kn(krune=kune),','',''),
(115,1,'VG','VG','VG+','moja stara,obrisana, oprana','',''),
(116,1,'NM','NM','NM','PP4kn,','',''),
(117,1,'NM','NM','NM','Srđan,','',''),
(118,1,'NM','NM','NM','191kn(P5€),','',''),
(119,1,'NM','NM','VG+','Jurman,obrisana','',''),
(120,1,'NM','NM','NM','Srđan,obrisana','',''),
(121,1,'NM','NM','NM','moja stara,obrisana','',''),
(122,1,'VG+','?','?','moja stara,','',''),
(123,1,'NM','?','?','moja stara,','',''),
(124,1,'NM','NM','NM','188kn(P5€),','',''),
(125,1,'NM','VG+','VG','Jurman,obrisana','pucka',''),
(126,1,'NM','NM','NM','179kn,','',''),
(127,1,'VG','G','G','Jurman,obrisana, oprana','pucka',''),
(128,1,'NM','NM','NM','P70kn(kune=krune),','',''),
(129,1,'NM','VG+','G','Jurman,obrisana','',''),
(130,1,'NM','NM','G','Jurman,obrisana','',''),
(131,1,'NM','P','P','Jurman,obrisana, oprana','šuška pucka',''),
(132,1,'NM','NM','NM','moja stara,','',''),
(133,1,'NM','NM','NM','165kn(PP€),','',''),
(134,1,'NM','NM','NM',',','',''),
(135,1,'NM','NM','NM',',','',''),
(136,1,'NM','NM','NM',',','',''),
(137,1,'G','P','VG+','sajam starina P0kn,obrisana, oprana','',''),
(138,1,'NM','NM','NM','moja stara,','',''),
(139,1,'G','G','G+','sajam starina,obrisana','preskače B strana',''),
(140,1,'NM','NM','NM','sajam ploča P0€,','',''),
(141,1,'NM','NM','VG+','Deklman,','',''),
(142,1,'NM','NM','NM','Deklman,','',''),
(143,1,'NM','NM','NM','P18kn(P9€),','',''),
(144,1,'NM','NM','NM','P70kn(kune=krune),','',''),
(145,1,'NM','NM','NM','P30kn(kune=krune),','',''),
(146,1,'NM','NM','NM','P00kn(kune=krune),','',''),
(147,1,'NM','NM','NM','PP0kn(kune=krune),','',''),
(148,1,'NM','NM','NM','300kn(40€),','',''),
(149,1,'NM','NM','NM','P30kn(kune=krune),','',''),
(150,1,'NM','NM','NM',',','',''),
(151,1,'VG+','NM','?','Vjeran 40.rođendan,','',''),
(152,1,'NM','NM','NM','PP5kn(30€),','',''),
(153,1,'NM','NM','?','moja stara,obrisana, oprana','','');








